### ISSUE TITLE
关于图灵机器人在QQ群内一次性回复两次的情况

### ISSUE THREAD

**Issue by theprimone** [richardchien/none-bot#11]
简单研究了一下，好像是因为我设置了这个`COMMAND_START.add('')`，导致了QQ群里边@机器人会导致机器人响应两次（一条是@的方式，一条没有@），请问有什么好的解决方法吗？

**Comment by richardchien** [comment]
这不会的吧，@ 是在进入命令之前就剥离了的，看下你的配置文件和代码？

**Comment by theprimone** [comment]
config.py配置如下：
```
from none.default_config import *

HOST = '0.0.0.0'
PORT = 8421

NICKNAME = {'nicename'}

SUPERUSERS = {我的QQ}
COMMAND_START.add('')
COMMAND_START.remove('/')  # 表情起始符号

TULING_API_KEY = '我的key'
```
至于图灵机器人代码就是copy的指南里的:joy:

**Comment by richardchien** [comment]
插件那边的配置文件呢

**Comment by theprimone** [comment]
好吧，尴尬了，折腾来折腾去发现酷Q的图灵机器人未停用，我记得我配置none-bot的图灵机器人就停用了的啊:joy:
换个问题吧，怎么在群里边回复某人消息的时候的@对方呢？好像文档没有提及啊

**Comment by richardchien** [comment]
需要结合起来看一下 [酷 Q 官方文档](https://d.cqp.me/Pro/CQ%E7%A0%81)、[CoolQ HTTP API 插件文档](https://cqhttp.cc/docs/#/Message)、[python-aiocqhttp 文档](https://github.com/richardchien/python-aiocqhttp#message-%E6%A8%A1%E5%9D%97)

**Comment by theprimone** [comment]
好的，我再研究一下。还有一个问题 我重新提个issue先

**Comment by richardchien** [comment]
> 啥意思？我现在也出现了回复两次的情况

酷Q 自带有一个图灵机器人插件，他那个是自带的没关……

**Comment by Coxxs** [comment]
建议以后有问题贴一下 酷Q 日志截图（
