### ISSUE TITLE
如何实现三级以上命令呢？

### ISSUE THREAD

**Issue by theprimone** [richardchien/none-bot#12]
跟着指南走，也就会二级命令的操作：
```
天气 成都
```
那么怎么实现像如下的三级命令呢？
```
天气 成都 后天
```

**Comment by richardchien** [comment]
这里 `天气 成都`，实际上进命令处理器之后，命令是 `天气`，参数是 `成都`，你的第二个例子，参数就是 `成都 后天`，因为这部分的切分方式因使用场景而异，比如翻译类的命令可能不能按空格切分，有些可能需要处理引号内的所有文本等等，所以这个 NoneBot 是不处理的，内容在 `session.current_arg`，你可以自行解析

**Comment by richardchien** [comment]
像你这个需求，可以使用 Python 自带的 [`shlex`](https://docs.python.org/3/library/shlex.html) 包，参考 https://github.com/richardchien/maruko/blob/master/maruko/plugins/schedule.py#L141

**Comment by theprimone** [comment]
好的 多谢大佬提供思路:thumbsup:
