### ISSUE TITLE
增加中断CommandSession的外部机制

### ISSUE THREAD

**Issue by waylonwang** [richardchien/none-bot#13]
用户在进行CommandSession的交互时出现“您有命令正在执行，请稍后再试”，这时用户只能等到timeout，没有任何办法，除非重启整个none应用，如果用户此时可以输入“终止命令”等之类的指令，强行kill掉session，则可以让用户退出本次session后进行其他command操作。

当前，在CommandSession的session处理中，输入的任何文字都会被解析为session中的内容，无法跳出session本身之外进行处理，这个“终止命令”无法被更底层的session调度方监控到并生效，所以应该要有类似操作系统的中断机制，使用“终止命令”之类的保留字来处理这个中断本身。

**Comment by richardchien** [comment]
[0.3.2](https://github.com/richardchien/none-bot/blob/master/CHANGELOG.md#v032) 版本新增了一些机制允许下面这样的代码来实现这个需求：

```python
@on_command('test')
async def _(session: CommandSession):
    await asyncio.sleep(20)
    await session.send('test')


@on_command('kill', privileged=True)
async def _(session: CommandSession):
    none.command.kill_current_session(session.bot, session.ctx)
```

同时，可通过配置 `SESSION_RUN_TIMEOUT` 来调整命令的超时时间（默认不超时）。
