### ISSUE TITLE
日志上没在处理信息

### ISSUE THREAD

**Issue by jyh111** [richardchien/none-bot#17]
会自动回复，在酷Q上的日志也会显示，但是文件夹的日志没有显示处理信息（但显示了开启 HTTP 服务器成功，开始监听 http://0.0.0.0:5700）
CQA-tuling\酷Q Air\app\io.github.richardchien.coolqhttpapi\log

**Comment by richardchien** [comment]
没有上报相关的日志吗

**Comment by jyh111** [comment]
恩

**Comment by jyh111** [comment]
@richardchien

**Comment by richardchien** [comment]
试试把 `log_level` 改成 `debug` 看看？
