### ISSUE TITLE
建议在cool_http_api.py中处理CQ码的转移并对群成员使用群名片作为昵称

### ISSUE THREAD

**Issue by waylonwang** [richardchien/none-bot#2]
1.根据酷Q的文档，消息中为避免CQ码产生歧义，指定了’[’、’]’、’&’、’,’须进行转义
2.群成员使用群名片而不是昵称来称呼更加和
为减少后续filter和command的修改，转义及群名片最好在cool_http_api.py中直接修改，我已修改实现，因我修改的其他文件包含了非公共的变更，就不推送pull requests给你了，如要实现，可以参考这个[代码变更](https://github.com/CCZU-DEV/xiaokai-bot/commit/a83ecfe0dad5f7660191ddbfa04bcbdf861c5b5d)

**Comment by richardchien** [comment]
转义这个问题我写的时候是有考虑的，对于发送消息（echo），因为用的是我另一个 coolq-http-api，我直接用了 `is_raw` 参数让他来自己转义，对于接收的消息，我当时想的是如果把编码后的字符再转回来可能会和 CQ 码混淆，不过现在想来这个可能是有点问题。

你能自己改当然最好啦～我其实感觉这个适配器这边我写的有点乱，对不同平台的适配基本上是凭直觉写，我想后面有时间的话要设计一套通用接口，包括发送、接收的那种，把图片、语音之类的消息格式也支持进来，这样也就不会出现 CQ 码转义的问题了；以及这个整体的程序框架可能也要重构一下。

如果你有兴趣的话我们到时候可以讨论讨论，不过可能要过一段时间，最近在忙一些别的事情。

最后也感谢你的支持～

**Comment by waylonwang** [comment]
嗯，我看到is_raw参数时也想到你可能是把转义的处理留个应用自己去解决了，只不过应用中去解决要么是通过一个统一的filter和echo来处理，要么散落在各个模块或函数中，这样都不如adapter来处理更加合适

我自己的代码会尽量保持独立，避免与你的框架产生耦合，等你忙完重构时我们可以讨论一些其他优化的地方，我先把想到的都已issue方式记录下来

**Comment by richardchien** [comment]
嗯嗯，另外 `is_raw` 是在调用 [/send_private_msg](https://richardchien.github.io/coolq-http-api/#/API?id=send_private_msg-%E5%8F%91%E9%80%81%E7%A7%81%E8%81%8A%E6%B6%88%E6%81%AF) 这个接口时候传的，对 xiaokai-bot 的插件是隐藏的，其实跟直接在 adapter 里转义是一样的了，其实也无所谓。

**Comment by richardchien** [comment]
现在发送消息时候，直接由调用者处理消息的格式了（包括 CQ 码），由于 `aiocqhttp` 提供了 `Message` 和 `MessageSegment` 类，使用已经足够方便了，再加上 `none` 提供了 expression 的支持（在一些表达方式中随机一个进行格式化，或调用函数生成，具体文档有空会写）。另外现在已经没有适配器了，完全依赖于酷 Q，因为实在精力有限，而且 CoolQ HTTP API 已经比较完善了。

这个 issue 先关了，内容已经和最新的 NoneBot 关联不大了。
