### ISSUE TITLE
用none开发的机器人推荐的部署方式是怎样呢？

### ISSUE THREAD

**Issue by yorushika** [richardchien/none-bot#21]
aiocqhttp中看到推荐用ASGI，但none框架下bot对象甚至都不推荐使用？

**Comment by richardchien** [comment]
跟 aiocqhttp 一样吧，NoneBot 的进阶文档我还没写，本来应该写在那里面的

**Comment by yorushika** [comment]
尝试了一下在init后获取none.get_bot()可以跑起来了，还有一个问题，我再开个issue吧。
