### ISSUE TITLE
「/echo/XXX」会报错

### ISSUE THREAD

**Issue by ImSingee** [richardchien/none-bot#25]
例如自带的 echo 命令输入「/echo/1」，控制台会报错
在文档中的「天气」插件，「/weather/1」会报错，但是「/天气/1」不会

**Comment by richardchien** [comment]
你的这个 `/echo/1` 应该意图是调用命令 `('echo', '1')` 吧，这个命令存在吗

另外发一下报错信息截图看看呢

**Comment by richardchien** [comment]
> 你的这个 `/echo/1` 应该意图是调用命令 `('echo', '1')` 吧

自带的 `echo` 命令是 `('echo',)`，调用方式应该是 `/echo XXXX`，`COMMAND_SEP` 这个配置是用来控制命令名字的分隔符的，而不是命令和参数之间的分隔符

**Comment by ImSingee** [comment]
不存在，但是如果调用的/echo/xxx 这样的就能解析出来 (echo,xxx) 然后提示命令不存在而不是抱错…
2018年12月21日 +0800 PM9:44 Richard Chien <notifications@github.com>，写道：

**Comment by richardchien** [comment]
我测试了下，确实报错了，我看看，应该是我代码的问题

**Comment by richardchien** [comment]
已经在 develop 分支修了，下个版本发

**Comment by richardchien** [comment]
已经在 v0.5.0 中修复
