### ISSUE TITLE
有没有办法存储一些仅在机器人运行期间有效的数据？

### ISSUE THREAD

**Issue by yorushika** [richardchien/none-bot#27]
比如`是否自动接收好友申请`，我本是想写在redis里，每次收到请求就`on_request`查询一次，但考虑到潜在的如果短时间内频繁收到好友申请就会造成redis频繁读写~~DDOS~~，因此如果能读取以后把这个数据存储到机器人当前的运行实例中会好很多。

**Comment by richardchien** [comment]
@yorushika 诶，完全可以在插件的 py 文件的全局作用于放一个变量来存呀

**Comment by yorushika** [comment]
我沙雕了(/ω＼)
