### ISSUE TITLE
建议：为 session.send 方法增加 at_sender 参数

### ISSUE THREAD

**Issue by ImSingee** [richardchien/none-bot#29]

**Comment by richardchien** [comment]
v0.5.1 已经加入，不过注意需要升级 python-aiocqhttp 到 0.6.7+

**Comment by yorushika** [comment]
> v0.5.1 已经加入，不过注意需要升级 python-aiocqhttp 到 0.6.7+

不翻issues发现不了系列😌话说这几个库有没有更新推送通知一类的？

**Comment by richardchien** [comment]
有，QQ 群 218529254 或者 Telegram 群 https://t.me/cqhttp_release，我写到 README 上吧

**Comment by yorushika** [comment]
奶思
