### ISSUE TITLE
有没有办法注册一个全局的「监控」？

### ISSUE THREAD

**Issue by ImSingee** [richardchien/none-bot#36]
需求是定义一个插件可以记录所有的消息备查

即任何消息都会触发这个命令、同时不会影响其他命令触发

**Comment by richardchien** [comment]
使用 aiocqhttp 的接口

```python
bot = none.get_bot()

@bot.on_message
async def _(bot, ctx):
    pass
```

**Comment by ImSingee** [comment]
OK 感谢！

希望把这个和 bot.on_meta_event 的写进 none 的文档吧，找了好久……

**Comment by ImSingee** [comment]
另外，似乎这种写法更符合 none 的风格

**Comment by richardchien** [comment]
噢噢等下，我刚刚写错了，确实是只有 `ctx` 这一个参数，具体你去看下 aiocqhttp 的 README
