### ISSUE TITLE
添加计划任务为什么不能发消息到群

### ISSUE THREAD

**Issue by tuheyuan** [richardchien/none-bot#9]
添加计划任务为什么不能发消息到群，我测试计划任务是运行的。
bot = none.get_bot() 
机器人对象也获取了。
但是发群消息不行
await bot.send_group_msg(group_id=672076603,message=f'现在{now.hour}点整啦！')
这一句就不执行了

**Comment by richardchien** [comment]
你是跑的文档里的示例吗，`group_id` 有改成你的吗，另外可以把

```python
except CQHttpError:
    pass
```

改成

```python
except CQHttpError as e:
    none.logger.exception(e)
```

看看是不是抛出了异常

**Comment by tuheyuan** [comment]
group_id已经改成我自己了，没有抛异常
